[package]
name = "gps-share"
version = "0.1.0"
authors = ["Zeeshan Ali <zeenix@gmail.com>"]

[dependencies]
serial = "0.3"
dbus = "^0.5"
dbus-macros = { git = "https://github.com/antoyo/dbus-macros-rs", branch = "master" }
chan = "0.1.19"
chan-signal = "0.2.0"
clap = "2.23.1"
libc = "^0.2.21"
